data:
  corpus:                                 
    name: 'Librispeech'                   # Specify corpus
    path: 'save/LibriSpeech'              # Path to raw LibriSpeech dataset
    test_path: 'save/LibriSpeech'         # Path to raw or augmented testing dataset
    dev_split: ['dev-clean']              # Name of data splits to be used as validation set
    test_split: ['test-clean']            # Name of data splits to be used as testing set
    bucketing: False                      # Enable/Disable bucketing
    batch_size: 1
    in_memory: False
  audio:
    num_freq: 1025
    num_mels: 80
    frame_length_ms: 50
    frame_shift_ms: 12.5
    preemphasis_coeff: 0.97
    sample_rate: 16000
    use_linear: False                      # Return Linear spectrogram
    # augmentation
    snr_range: [-1]
    time_stretch_range: [1.0, 1.0]
    inverse_prob: 0.0
  text:
    mode: 'subword'                       # 'character'/'word'/'subword'
    vocab_file: 'tests/sample_data/subword.model'

model:                                    # Model architecture
  delta: 2
  ctc_weight: 1.0                         # Weight for CTC loss
  encoder:
    cnn:                                  # 4x reduction on time feature extraction
      type: 'vgg'
    module: 'LSTM'                        # 'LSTM'/'GRU'/'Transformer'
    bidirection: True
    dim: [320,320,320,320,320]
    dropout: [0,0,0,0,0]
    layer_norm: [False,False,False,False,False]
    proj: [True,True,True,True,True]      # Linear projection + Tanh after each rnn layer
    sample_rate: [1,1,1,1,1]
    sample_style: 'drop'                  # 'drop'/'concat'
  attention:
    mode: 'loc'                           # 'dot'/'loc'
    dim: 300
    num_head: 1
    v_proj: False                         # if False and num_head>1, encoder state will be duplicated for each head
    temperature: 1                        # scaling factor for attention
    loc_kernel_size: 100                  # just for mode=='loc'
    loc_kernel_num: 10                    # just for mode=='loc'
  decoder:
    module: 'LSTM'                        # 'LSTM'/'GRU'/'Transformer'
    dim: 320
    layer: 1
    dropout: 0
hparas:
  spec: False
  wave: True
tts:
  layer_num: 9
  num_layers: 4
  type: 'highway'
src: 'dummy' # to be replaced by bash script
