data:
  corpus:                                 # Pass to dataloader
    # The following depends on corpus
    name: 'Librispeech'                   # Specify corpus
    path: '/pth/to/LibriSpeech'
    train_split: ['librispeech-lm-norm.txt']
    dev_split: ['dev-clean']
    bucketing: True
    batch_size: 128

  text:
    mode: 'subword'                     # 'character'/'word'/'subword'
    vocab_file: 'tests/sample_data/subword.model'

hparas:                                   # Experiment hyper-parameters
  valid_step: 10000
  max_step: 100000000
  optimizer: 'Adam'
  lr: 0.0001
  eps: 0.00000001
  lr_scheduler: 'fixed'                    # 'fixed'/'warmup'
  
model:                                     # Model architecture
  emb_tying: False                         # https://arxiv.org/pdf/1608.05859.pdf
  emb_dim: 128
  module: 'LSTM'                           # 'LSTM'/'GRU'
  dim: 256
  n_layers: 2
  dropout: 0.0
  
  
